name: Angular Deployment pages
on:
  workflow_dispatch:
    inputs:
      branch_to_build:
        description: 'Branch to build and deploy Angular. Select Branch'
        required: false
  pull_request:
    branches: [master, main]
    
jobs:
  event:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.22.5
        uses: actions/setup-node@v1
        with:
          node-version: '12.22.5'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:ci
      - name: Test
        run: npm run test:ci
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
        
      
      
