# This is a basic workflow to help you get started with Actions

name: 'Deploy on Github Pages'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
defaults:
  run: 
    working-directory: ./frontend
jobs:
  deploy_ghpages:
    name: Push to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Use node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx ng build --base-href /tastydra22/
      # Workflow dispatch event that pushes the current version to the release branch.
      # From here the secondary production deployment workflow will trigger to build the dependencies.
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: frontend/dist/tasty
          clean: true
          single-commit: true
